version: '3.4'

networks:
  service: 
    driver: bridge

services:
  api-service:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: api-service
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7002:80"
    depends_on:
      - "api-service-db"
      - "redis-cache-service"
    links:
      - "redis-cache-service"
    networks:
      - service
  api-service-db:
    image: postgres
    container_name: api-service-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=developer2023
      - POSTGRES_DB=EducationDB
    ports:
      - "5433:5432"
    volumes:
     - api-service-db-data:/var/lib/postgresql/data
    networks:
      - service

  redis-cache-service:
    image: redis
    container_name: redis-cache-service
    restart: always
    ports:
     - "7003:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    # sysctls:
    #  - sysctl vm.overcommit_memory=1
    volumes:
        - redis-cache-service-data:/data
        - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - service
volumes:
  api-service-db-data:
  redis-cache-service-data:
    